### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/belong#1]
Some things that would be nice:

- [x] Init command
- [ ] Proper integration testing
- [ ] Codecov on CI 
- [ ] Logging
- [ ] Easy to add navbar items
- [ ] RSS feed
- [ ] Page categories
- [ ] Build binaries (for tags) and automatically post to GitHub releases
- [ ] Code example anchors? Like mdbook
- [ ] Search bar and page keywords
